export const SWR_CACHE_KEYS = {
  me: "/me",
  systems: "systems/",
  projects: "projects/",
  groupedProjects: "projects/group",
  system: "system/",
  clients: "clietns/",
  client: "client/",
  sectors: "sectors/",
  sector: "sector/",
  departments: "departments/",
  department: "department/",
  notes: "notes/",
  note: "note/",
}
